/**
 * AI-Generated Mark Extension
 * Tracks content generated by AI (Council, Refactor, Expand, Simulate)
 * 
 * This mark is invisible by default but allows us to:
 * - Track AI-generated content
 * - Apply global visual feedback via CSS
 * - Filter/query AI content programmatically
 */

import { Mark, mergeAttributes } from '@tiptap/core';

export interface AiGeneratedOptions {
  HTMLAttributes: Record<string, any>;
}

declare module '@tiptap/core' {
  interface Commands<ReturnType> {
    aiGenerated: {
      /**
       * Set the AI-generated mark
       */
      setAiGenerated: () => ReturnType;
      /**
       * Toggle the AI-generated mark
       */
      toggleAiGenerated: () => ReturnType;
      /**
       * Unset the AI-generated mark
       */
      unsetAiGenerated: () => ReturnType;
    };
  }
}

export const AiGenerated = Mark.create<AiGeneratedOptions>({
  name: 'aiGenerated',

  addOptions() {
    return {
      HTMLAttributes: {},
    };
  },

  parseHTML() {
    return [
      {
        tag: 'span[data-author="ai"]',
      },
    ];
  },

  renderHTML({ HTMLAttributes }) {
    return [
      'span',
      mergeAttributes(this.options.HTMLAttributes, HTMLAttributes, {
        'data-author': 'ai',
        // Subtle debug underline (can be removed in production)
        // style: 'text-decoration: underline; text-decoration-style: dotted; text-decoration-color: rgba(147, 51, 234, 0.3);',
      }),
      0,
    ];
  },

  addCommands() {
    return {
      setAiGenerated:
        () =>
        ({ commands }) => {
          return commands.setMark(this.name);
        },
      toggleAiGenerated:
        () =>
        ({ commands }) => {
          return commands.toggleMark(this.name);
        },
      unsetAiGenerated:
        () =>
        ({ commands }) => {
          return commands.unsetMark(this.name);
        },
    };
  },
});

export default AiGenerated;
